engines:
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "phpmd.xml"
  markdownlint:
    enabled: true
ratings:
  paths:
    - "**.php"
exclude_paths:
  - examples/**/*
  - tests/**/*
  - "**/vendor/**/*"
